"""add webauthn fields

Revision ID: 628bcf5fd887
Revises: 8a1fbcfbe615
Create Date: 2026-09-25 13:35:11.038747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628bcf5fd887'
down_revision: Union[str, Sequence[str], None] = '8a1fbcfbe615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfa_pending_tokens', sa.Column('webauthn_challenge', sa.Text(), nullable=True))
    op.add_column('user_mfa_methods', sa.Column('credential_id', sa.String(length=255), nullable=True))
    op.add_column('user_mfa_methods', sa.Column('public_key', sa.Text(), nullable=True))
    op.add_column('user_mfa_methods', sa.Column('sign_count', sa.Integer(), nullable=False))
    op.add_column('user_mfa_methods', sa.Column('webauthn_challenge', sa.Text(), nullable=True))
    op.create_index(op.f('ix_user_mfa_methods_credential_id'), 'user_mfa_methods', ['credential_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mfa_methods_credential_id'), table_name='user_mfa_methods')
    op.drop_column('user_mfa_methods', 'webauthn_challenge')
    op.drop_column('user_mfa_methods', 'sign_count')
    op.drop_column('user_mfa_methods', 'public_key')
    op.drop_column('user_mfa_methods', 'credential_id')
    op.drop_column('mfa_pending_tokens', 'webauthn_challenge')
    # ### end Alembic commands ###
