"""add storage_files

Revision ID: 8a1fbcfbe615
Revises: 30776ef693c1
Create Date: 2026-09-23 06:33:39.048821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1fbcfbe615'
down_revision: Union[str, Sequence[str], None] = '30776ef693c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('received_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_files_owner_id'), 'storage_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_storage_files_storage_key'), 'storage_files', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_files_storage_key'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_owner_id'), table_name='storage_files')
    op.drop_table('storage_files')
    # ### end Alembic commands ###
